### ISSUE TITLE
Tutorial: How to fix "This client has not been approved to access this resource."

### ISSUE THREAD

**Issue by sebbler1337** [kevinongko/vue-instagram#11]
Hey guys,

just wanted to share my findings on the problem that i was fighting with for an hour:

If you have the message described in the headline just follow those steps:

**1. Sign into your IG profile at https://www.instagram.com/developer/
2. Create a Client
3. Go to this URL https://api.instagram.com/oauth/authorize/?client_id=[YOUR_CLIENT_ID]&redirect_uri=[YOUR_REDIRECT_URI]&scope=public_content&response_type=token
REMEMBER TO FILL IN YOUR FRESHLY CREATED CLIENT ID AND YOUR REDIRECT URI (with 'http://' in front)
4. Take the new token out of the response (in the url bar) and put it into the token prop of the vue-instagram component**

if you still get {"error_type": "OAuthForbiddenException", "code": 403, "error_message": "Implicit authentication is disabled"} try unchecking "Disable implicit OAuth" in the Security tab on your newly created client.

If you have any questions, feel free to ask,

Sebastian

**Comment by kevinongko** [comment]
Hi @sebbler1337, thanks for the guide, however this is not the proper place to post a guide.
I'll move it to wiki :)
