### ISSUE TITLE
Unable to use with Vuepress / SSR (browser-jsonp?)

### ISSUE THREAD

**Issue by m2de** [kevinongko/vue-instagram#21]
Hi. Thanks for your package. Initially this worked really well, however I'm trying to use it in a Vuepress build, which also work fine when running in dev mode, however when trying to build the project i get a `ReferenceError: window is not defined` error.

My initial guess would be that this is caused by the browser-jsonp library. Would you consider switching this to a node compatible library like axios or similar? I'd be happy to have a go at this and make a PR but wanted to see what your view on it was first.

Cheers!

**Comment by kevinongko** [comment]
Thanks, updated to use axios
https://github.com/kevinongko/vue-instagram/releases/tag/v3.0.0
