### ISSUE TITLE
Issue with Content Security Policy (CSP)

### ISSUE THREAD

**Issue by sebj54** [kevinongko/vue-instagram#23]
Hi there!

Thank you for your amazing plugin, it's amazing!

I just have on concern about Content Security Policy. I added these rules (I removed the non-relevant ones): 

```
default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' https://api.instagram.com; img-src 'self' https://scontent.cdninstagram.com; 
```

I still have errors about CSP in my console (there wasn't any before I added this plugin): 

![image](https://user-images.githubusercontent.com/5880435/52434372-70e3ec80-2b0f-11e9-921b-2b28308fef86.png)

The picture above is in French but it means: 
"The page settings have prevented the loading of a resource to be evaluated".

Are these evaluated scripts necessary? 

Thanks for your help! 👍

**Comment by kevinongko** [comment]
Hi @sebj54, 
I never had this problem, it could be settings from your web server / hosting provider
maybe try use the latest version and check it again https://github.com/kevinongko/vue-instagram/releases/tag/v3.0.0
