### ISSUE TITLE
Please document the "feed" object

### ISSUE THREAD

**Issue by philBrown** [kevinongko/vue-instagram#24]
Some simple documentation showing the properties of each `feed` object would be very handy.

Your example code could also use some work. I would recommend you add the template code from this comment ~ https://github.com/kevinongko/vue-instagram/issues/1#issuecomment-315660203

**Comment by kevinongko** [comment]
Hi @philBrown,

- the properties of feed object are response from instagram API, please refer to instagram API docs for the object details
- the example code can be found in the readme https://github.com/kevinongko/vue-instagram#usage or docs/index.html folder
