### ISSUE TITLE
Loading slot?

### ISSUE THREAD

**Issue by mrodrig** [kevinongko/vue-instagram#25]
Hi,

Does this support a template slot while loading (eg. waiting for the API to respond)? If so, could you please point me to some documentation for it? I can't seem to find anything on it if there is such a thing.

Thanks for creating this cool Vue component!

**Comment by kevinongko** [comment]
Thanks, updated to support loading slot, please refer to docs/index.html for example
https://github.com/kevinongko/vue-instagram/releases/tag/v3.0.0
