### ISSUE TITLE
Does this work with new 2019 Instagram Graph API?

### ISSUE THREAD

**Issue by tomkeysers** [kevinongko/vue-instagram#27]
Because suddenly my access token has become invalid and I can't register a client anymore in the old way.

And the provided demo also doesn't seem to work?

**Comment by ahoiadigital** [comment]
It's not working for me as well. I'm trying to find an alternate solution, please let me know if you figure it out

**Comment by kevinongko** [comment]
Hello @tomkeysers, @ahoiadigital 

the demo is not working because my access token has expired, using valid token will still works, I've tried generating new access token using this https://instagram.pixelunion.net/ and it works

working demo: https://kevinongko.github.io/vue-instagram/

**Comment by sebj54** [comment]
Hi @kevinongko, the website at https://instagram.pixelunion.net/ seems offline. Any suggestion to get an access token?
