### ISSUE TITLE
Is this component fully styleable and is the content fully customizable?

### ISSUE THREAD

**Issue by rchrdnsh** [kevinongko/vue-instagram#4]
I like the initial idea of your component, but for some clients I would only need to show pictures, not comments or captions or anything else, so is that possible? I would also want the styling stripped down to match the aesthetic of a clients app, so is this possible as well?

Thank you in advance for your time :-)

**Comment by kevinongko** [comment]
Hi @rchrdnsh ,

yes this component is fully customizable to your need, it utilize [scoped slot](https://vuejs.org/v2/guide/components.html#Scoped-Slots) so each instance can have different style.

Check out the example code at the [readme](https://github.com/kevinongko/vue-instagram/blob/master/README.md#usage) file and [here](https://brewsuniq.com/) is the example usage in real production site.

**Comment by rchrdnsh** [comment]
schweet, thanks :-)
