### ISSUE TITLE
How do i generate an 'access token'?

### ISSUE THREAD

**Issue by rchrdnsh** [kevinongko/vue-instagram#5]
This seems really obtuse and confusing, so how do I generate an access token? Going through Instagram's docs is like slowly hammering nails into my skull while sitting in a kiddie pool filled with electric eels...

Do you have a recommended workflow for this? Will getting an Instagram access token work while in local development mode? Any resources that you could recommend to get through this insanity?

Thank you in advance! XD

**Comment by rchrdnsh** [comment]
I got some sort of access token by going to this pixel union site, but now i'm getting this error message:

This client has not been approved to access this resource.

I have literally no idea what i'm doing here. None. At. All. Now I'm trying to "Register new client ID' or some nonsense and I got to:

valid redirect URI's

no idea what that means...

...literally any information on this subject that makes any sense to a normal human being that you can share would be amazing XD XD XD

**Comment by kevinongko** [comment]
Hi @rchrdnsh ,

Here what I do:
1. go to https://www.instagram.com/developer/clients/manage/
2. Click "Register a new client"
3. Fill in the required form, remember to fill the "Valid redirect URIs"
4. After creating the client, now click "Manage" the client u will find the client secret and ID
5. paste those ID and secret to the form at https://rudrastyh.com/tools/access-token
click the "Generate Access Token" then it will generate a very long numbers, this is the access token u need

**Comment by rchrdnsh** [comment]
ok, thank you, I'll give this a try :-)
