### ISSUE TITLE
Add filtering by String

### ISSUE THREAD

**Issue by jwkicklighter** [kevinongko/vue-instagram#7]
Love the component, looking forward to adding this to a project I'm working on!

Would it be possible to add filtering by a specific keyword/hashtag? I'm not familiar with the Instagram API, but I see that the endpoint you use is specifically a user search. Ideally, the component would be able to search for a specific hashtag from within a specific user's feed.

Typing it out like that, it could honestly be something that even happens in the client if this isn't an endpoint that Instagram provides:

- Retrieve list of user's feed items
- Filter through them to only show items with specific criteria
- Fetch the images/comments/etc. for whatever is left after the filter

Would be happy to take a look at implementing the latter solution, if you're open to contributions.

**Comment by kevinongko** [comment]
Hi @jwkicklighter,

I just added `tags` props in v1.3.1 to filter posts by hashtag.
Also feel free to submit PR if you want to contribute, thanks 😄

**Comment by jwkicklighter** [comment]
@kevinongko Just took a look, and that's basically exactly what I would have done. Thanks!
