### ISSUE TITLE
How do I use vue-instagram with waterfall? 

### ISSUE THREAD

**Issue by rlam3** [kevinongko/vue-instagram#8]
How do I use vue-instagram with waterfall? 
https://github.com/MopTym/vue-waterfall

@kevinongko

**Comment by freddyamsterdam** [comment]
I think the short answer is: "you don't!". Vue Instagram is a component.

From what I can tell, Vue Waterfall expects an array of images for which – at least in this particular case – you'll need to perform a call to the Instagram API. This should give you a clue as to how you can retrieve your Instagram feed:

https://github.com/kevinongko/vue-instagram/blob/master/src/vue-instagram.vue#L71

Good luck.

**Comment by kevinongko** [comment]
Thanks for the explanation @freddyamsterdam
